Donation_Test/urls.py
from django.urls import path
from .views import index,display_donators,make_donations,tembak_json

urlpatterns = [
   path('donate/',index, name='donate'),
   path('display_donators/',display_donators,name='display_donators'),
   path('makedonation/',make_donations,name='make_donations'),
   path('tembak_json/',tembak_json,name='tembak_json')
]

Login/urls.py
from django.urls import path
from .views import login,logout


urlpatterns = [
    
    path('login/',login,name='login'),
    path('logout/',logout,name='logout')
    
]

Newsroom/urls.py
from django.urls import path
from .views import Newsroom

urlpatterns = [
   path('',Newsroom, name='Newsroom'),
]

Testimoni/urls.py
from django.urls import path
from django.conf.urls import url
from .views import indexs,testimoni_handler,tembak_json_testi,createTestimoni,showTestimoni
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
   path('',indexs, name='testimoni'),
#    url(r'^testimoni/', testimoni, name= 'testimonii'),
   path('write_testi/',testimoni_handler,name='write_testi'),
   path('json_testi/',tembak_json_testi,name='json_testi'),
#    path('',indexs, name='indexs'),
   # url(r'^testimoni/', testimoni, name= 'testimonii')
   url(r'^createTestimoni/', createTestimoni, name='createTestimoni'),
   url(r'^showTestimoni/', showTestimoni, name='showTestimoni'),
]

urlpatterns += staticfiles_urlpatterns()

homepage/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index
#from Testimoni.views import indexs

urlpatterns = [
    #url(r'^$', index, name='index'),
    path('',index,name='index'),
    # path('login/',login,name='login'),
    # path('logout/',logout,name='logout')
    #path('testi/',indexs,name='testimoni')
]

team6/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('homepage.urls','homepage'),namespace='homepage')),
    path('helloworld/',include(('Hello_World.urls','Hello_World'),namespace='Hello_World')),
    path('register_test/',include(('Register_Test.urls','Register_Test'),namespace='Register_Test')),
    path('donation_test/',include(('Donation_Test.urls','Donation_Test'),namespace='Donation_Test')),
    path('news/',include(('newsapp.urls','newsapp'),namespace='newsapp')),
    path('newsroom/',include(('Newsroom.urls','Newsroom'),namespace='Newsroom')),
    path('testimoni/',include(('Testimoni.urls','Testimoni'),namespace='Testimoni')),
    path('auth/',include('social_django.urls', namespace='social')),
    path('user_login/',include(('Login.urls','Login'),namespace='Login'))
	
    #path('donation_test/',include(('Donation_Test.urls','Donation_Test'),namespace='Donation_Test'))

]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
#from Testimoni.views import indexs

response = {}

def index(request):
    return render(request, "index.html",response)
# def login(request):
#     return render(request,"login.html",response)
# def logout(request):
#     request.session.flush()
#     return login(request)

homepage/templates/partials/footer.html
<!--
<div id="container">
	<div class="row" id="footer">
		{% load static %}
		<p id="get-in-touch">GET IN TOUCH: </p>

		<i class="fa fa-twitter-square" href="https://twitter.com/CrowdfundCs?lang=en twitter" style="font-size:36px; color: #4150AF"></i>
		<i class="fa fa-instagram" style="font-size:36px; color: #4150AF"></i>
		<i class="fa fa-at" style="font-size:36px; color: #4150AF"></i>

		<p id="cred">© 2018 by Team 6</p>
	</div>
</div>
-->

<div class="card text-center">
	<div class="card-body">
		<h5 class="card-title">Get the latest info and news</h5>
		<h5 class="card-title">about CS-Crowdfund programs and activity</h5>
		<a href="https://twitter.com/CrowdfundCs" class="fa fa-twitter-square" style="font-size:72px"></a>
		
		<a>  </a>

		<a href="https://www.instagram.com/cs.crowdfund/" class="fa fa-instagram" style="font-size:72px"></a>
	</div>
</div>

homepage/templates/partials/header.html
<nav class="navbar navbar-expand-lg mx-auto" style="background-color: #4150AF; width: 800px;">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="navbar-toggler-icon" style="color: white;"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarToggleExternalContent">
	    <div class="navbar-nav">
	      <a class="nav-item nav-link" href="{% url 'homepage:index' %}">Home</a>
	      <a class="nav-item nav-link" href="{% url 'Newsroom:Newsroom' %}">Newsroom</a>
	      <a class="nav-item nav-link" href="{% url 'Register_Test:index' %}">Register</a>
	      <a class="nav-item nav-link" href="{% url 'Donation_Test:donate' %}">Donate</a>
				<a class="nav-item nav-link" href="{% url 'Donation_Test:display_donators' %}">Your Donations</a>
				<a class="nav-item nav-link" href="{% url 'Login:login' %}">Login</a>
				<a class="nav-item nav-link" href="{% url 'Login:logout' %}">Logout</a>
	      <a class="nav-item nav-link" href="{% url 'Testimoni:testimoni' %}">Testimonials</a>
	    </div>
	</div>
</nav>