Login/urls.py
from django.urls import path
from .views import login,logout


urlpatterns = [
    
    path('login/',login,name='login'),
    path('logout/',logout,name='logout')
    
]

Register_Test/urls.py
from django.urls import path
from .views import add_donatur,index


urlpatterns = [
   path('register/',index, name='index'),
   path('add_donatur/',add_donatur,name='add_donatur')

]

team6/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('homepage.urls','homepage'),namespace='homepage')),
    path('helloworld/',include(('Hello_World.urls','Hello_World'),namespace='Hello_World')),
    path('register_test/',include(('Register_Test.urls','Register_Test'),namespace='Register_Test')),
    path('donation_test/',include(('Donation_Test.urls','Donation_Test'),namespace='Donation_Test')),
    path('news/',include(('newsapp.urls','newsapp'),namespace='newsapp')),
    path('newsroom/',include(('Newsroom.urls','Newsroom'),namespace='Newsroom')),
    path('testimoni/',include(('Testimoni.urls','Testimoni'),namespace='Testimoni')),
    path('auth/',include('social_django.urls', namespace='social')),
    path('user_login/',include(('Login.urls','Login'),namespace='Login'))
	
    #path('donation_test/',include(('Donation_Test.urls','Donation_Test'),namespace='Donation_Test'))

]

Register_Test/models.py
from django.db import models

# Create your models here.
class Register(models.Model):
    name = models.CharField(max_length=200)
    dob = models.DateField()
    email = models.EmailField(max_length=70, null=True, blank=True)
    password =  models.CharField(max_length=100)
    password_verif = models.CharField(max_length=100)

Register_Test/forms.py
from django import forms
from .models import Register
#from django.core.validators import email_re
from django.core.exceptions import ValidationError


class Register_Form(forms.ModelForm):
    #dob = forms.DateInput(attrs={'type': 'date'}, label="Date of Birth")
    password = forms.CharField( 
    widget=forms.PasswordInput(render_value=False), 
    label="Your Password")
    password_verif = forms.CharField( 
    widget=forms.PasswordInput(render_value=False), 
    label="Verify Your Password"
)
    class Meta:
        model = Register
        fields =[
            'name',
            'dob',
            'email',
            'password',
            'password_verif',

        ]
        widgets = {
            'dob': forms.DateInput(attrs={'type': 'date'}),
        }

    # def bersih_email(self):
    #     #   print("berhasil masuk ke clean_email")
    #       print("keeksekusi bersih_email")
    #       data = self.cleaned_data['email']
    #       if Register.objects.filter(email=data).count() > 0:
    #           raise forms.ValidationError("We have a user with this user email-id")
    #       return data
    # # def save(self, *args, **kwargs):
    # #     # ... other things not important here
    # #     self.email = self.email.lower().strip() # Hopefully reduces junk to ""
    # #     if self.email != "": # If it's not blank
    # #         if not email_re.match(self.email): # If it's not an email address
    # #             raise ValidationError(u'%s is not an email address, dummy!' % self.email)
    # #     if self.email == "":
    # #         self.email = None
    # #     super(Register, self).save(*args, **kwargs)
    

    # def bersih(self):
    #     # print("berhasil masuk ke clean")
    #     print("keeksekusi bersih")
    #     form_data = self.cleaned_data
    #     if form_data['password'] != form_data['password_verif']:
    #         self._errors["password"] = ["Password do not match"] # Will raise a error message
    #         del form_data['password']
    #     return form_data


    

Register_Test/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from .models import Register
from .forms import Register_Form

# Create your views here.
response = {}

def index(request):

     response['Register_Data'] = Register.objects.all()
     response['register_form'] = Register_Form
     return render(request, 'form_test.html', response)

def add_donatur(request):
    # print("berhasil masuk ke donatur")
    # response['Register_Data'] = Register.objects.all()
    # response['register_form'] = Register_Form
    # response['display'] = ""
   
    form = Register_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        var =  Register.objects.all()
        cant_login = False
        response['name'] = request.POST['name']
        response['dob'] = request.POST['dob']
        response['email'] = request.POST['email']
        response['password'] = request.POST['password']
        response['password_verif'] = request.POST['password_verif']
        response["display"] = "Apparently there is something wrong with password verification"
        if (response['password']!=response['password_verif']):
            cant_login=True
            #response["display"] = "Apparently there is something wrong with password verification"
            messages.error(request, 'Apparently it is either your email is already registered or there is something wrong with password verification')
        for data in var:
            if (data.email==response['email']):
                cant_login = True
                #response["display"] = "Apparently your email is already registered"
                messages.error(request, 'Apparently it is either your email is already registered or there is something wrong with password verification')
                break
        # if (cant_login):
        #     response["display"] = "Apparently there is something wrong with password verification"
        if (cant_login==False):
            register = Register(name=response['name'],
                       dob=response['dob'],
                       email=response['email'],
                       password=response['password'],
                       password_verif=response['password_verif']

            )
            print("berhasil")
            register.save()
            response["display"]="Registration Success! You can proceed to Donation"
            messages.success(request, 'Registration Success! You can proceed to Donation')
        else:
            pass#response["display"] = "Apparently there is something wrong with password verification"

        
       
             
            
        
            
            
            
    return HttpResponseRedirect('/register_test/register/')
    #return render(request, 'form_test.html', response)

Register_Test/templates/form_test.html
{% extends "layout/base.html" %}
{% load static %}
 {% load staticfiles %}

<!--<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% load static %}
	   
        <title>CS-CrowdFunding</title>
    </head>-->

    
    {% block content %}
    
    <body>
	
	<div id="container-fluid">
	  <div id="content">
	    <div id="photo" style="float:left">
	      <a href="http://tinypic.com?ref=miny39" target="_blank"><img style="max-width:100%;height:auto;margin-left:20px;margin-top:110px" src="http://i66.tinypic.com/miny39.jpg" class="img-fluid" border="0" alt="Image and video hosting by TinyPic"></a>
	    </div>

	    <div id="fill">
	      <div id="title" style="float">
            <h1><b>REGISTER YOURSELF</b></h1>
			<h2 id="head2">Please fill in the register form</h2>
		  </div>
           
          <div class="row">
            <div class="col-md-6">
              <form id="form" style="align:center" method="POST" action="{% url 'Register_Test:add_donatur' %}"  >
                {% csrf_token %}
                <b>{{ register_form.as_p }}</b>
                <button type="submit" class="registerbtn">Register</button>
              </form>
    
            </div>       
          </div>

               
          <div class="row">
            <div class="col-md-6">
              {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
              </ul>
              {% endif %}
              <!--<p>   {{display}}  </p>-->

            </div>   
          </div>
		</div>
	  </div>
	</div>
           
    </body>
    {% endblock %}